schema_version = "1.0.0"
id = "wittyming_color_palette"
name = "Color Palette"
version = "1.2.3"
tagline = "Record and drag material node colors in the Shader Editor"
maintainer = "WittyMing"
type = "add-on"
website = "https://space.bilibili.com/263206115"
tags = ["Node", "User Interface"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 WittyMing"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
